name: Feature / Enhancement
description: Propose new functionality with acceptance criteria
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
    validations:
      required: true
  - type: textarea
    id: outcome
    attributes:
      label: Desired Outcome
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      placeholder: |
        - AC-1:
        - AC-2:
    validations:
      required: true
  - type: textarea
    id: constraints
    attributes:
      label: Constraints / Environment
    validations:
      required: false
